UniqueNumbers = set()
# a1=int(input("Enter Number present in a1:"))
# a1=int(input("Enter Number present in a1:"))
# a1=int(input("Enter Number present in a1:"))
# a1=int(input("Enter Number present in a1:"))
# a1=int(input("Enter Number present in a1:"))
# a1=int(input("Enter Number present in a1:"))
# a1=int(input("Enter Number present in a1:"))
UniqueNumbers.add(int(input("1st Number:")))
UniqueNumbers.add(int(input("2nd Number:")))
UniqueNumbers.add(int(input("3rd Number:")))
UniqueNumbers.add(int(input("4th Number:")))
UniqueNumbers.add(int(input("5th Number:")))
UniqueNumbers.add(int(input("6th Number:")))
UniqueNumbers.add(int(input("7th Number:")))
UniqueNumbers.add(int(input("8th Number:")))
# UniqueNumbers.add(input("2nd Number:"))
# UniqueNumbers.add(input("3rd Number:"))
# UniqueNumbers.add(input("4th Number:"))
# UniqueNumbers.add(input("5th Number:"))
# UniqueNumbers.add(input("6th Number:"))
# UniqueNumbers.add(input("7th Number:"))
# UniqueNumbers.add(input("8th Number:"))
print(UniqueNumbers)